apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goalixa-api

resources:
  - api-gateway-configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml

images:
  - name: YOUR_REGISTRY/bff-service
    newName: harbor.goalixa.com/goalixa-bff/api-gateway
    newTag: latest  # Change this to specific commit SHA for each deployment

commonLabels:
  app.kubernetes.io/name: api-gateway
  app.kubernetes.io/component: api-gateway
  app.kubernetes.io/part-of: goalixa
